### ISSUE TITLE
A way to run test.py on Ubuntu 20.04 (python 3.8)

### ISSUE THREAD

**Issue by thima2017** [ialhashim/DenseDepth#139]
Seems there is no tensorflow 1.* in pip3 for python 3.8. And the latest tensorflow (currently 2.3.0) doesn't work with Ubuntu 20.04's keras. So I installed the latest keras (2.4.3) and the latest tensorflow (2.3.0) with pip3
```
$pip3 install keras tensorflow-gpu
```
Then I got this issue
```
/New/DenseDepth/layers.py", line 9, in __init__
    self.data_format = K.normalize_data_format(data_format)
AttributeError: module 'keras.backend' has no attribute 'normalize_data_format'
```
I found a solution from Mete Han Kahraman there https://stackoverflow.com/a/53442550
I added the following after import section in layers.py:
```
def normalize_data_format(value):
    if value is None:
        value = K.image_data_format()
    data_format = value.lower()
    if data_format not in {'channels_first', 'channels_last'}:
        raise ValueError('The `data_format` argument must be one of '
                         '"channels_first", "channels_last". Received: ' +
                         str(value))
    return data_format
```
Then deleted ```K.``` in this string:
```
        self.data_format = K.normalize_data_format(data_format)
```
Also to solve issue #138 I changed that string (line 38 in non-modified version)
```
        return tf.image.resize_images(inputs, [height, width], method=tf.image.ResizeMethod.BILINEAR, align_corners=True)
```
to this
```
        return tf.image.resize(inputs, [height, width], method=tf.image.ResizeMethod.BILINEAR)
```
A link with partial solution of the last issue I used
https://better-coding.com/solved-tensorflow-attributeerror-module-tensorflow-_api-v2-image-has-no-attribute-resize_images/

[layers.py.zip](https://github.com/ialhashim/DenseDepth/files/5007835/layers.py.zip)

**Comment by thima2017** [comment]
And before that all I copied the pretrained data to DenseDepth directory. The dir with test.py.

**Comment by myselfHimanshu** [comment]
How to run test.py predictions on GPU? I have CUDA Version: 10.2

**Comment by thima2017** [comment]
I guess to run it on gpu installing of ```tensorflow-gpu ``` is enough.
```
pip3 uninstall tensorflow
pip3 install tensorflow-gpu
```

**Comment by thima2017** [comment]
A modified version of test.py that takes png images (640x480) from input directory and outputs outputs to output directory. 
[test2.py.zip](https://github.com/ialhashim/DenseDepth/files/5010431/test2.py.zip)
For some reason outputs are 320x240.

**Comment by ialhashim** [comment]
@thima2017 the expected outputs are half the input. You could modify the decoder to upsample back to 640x480 but we didn't see any major improvements and it just makes training slower.

**Comment by 3dsf** [comment]
@ialhashim @thima2017 
**Big thanks to both of you**
I have a **conda install** working on Fedora see [my notes to self](https://www.reddit.com/r/dsf/comments/ipwdsz/note_to_self_papers_i_need_to_reevaluate/g4ymn9k?utm_source=share&utm_medium=web2x&context=3)
I struggled a lot to get the GPU working, even thought I could see it through the python command line.  `cupti` from the main channel instead of from the nvidia channel, is what fixed it (but, currently only suspect why)
